name: it_kqt_mood
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
flutter:
  uses-material-design: true
  assets:
    - assets/presets/
    - assets/icons/

dependencies:
  freezed_annotation: ^2.4.4
  flutter:
    sdk: flutter

  # ðŸŒŸ ÐžÑÐ½Ð¾Ð²Ð½Ñ‹Ðµ
  provider: ^6.0.5
  flutter_svg: ^2.0.10+1
  collection: ^1.18.0
  json_annotation: ^4.9.0

  # ðŸ Ð”Ð»Ñ ÑÑ‚Ð°Ñ€Ð¾Ð¹ Ð»Ð¾Ð³Ð¸ÐºÐ¸ Ð¸Ð· features/day
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0

dev_dependencies:
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  json_serializable: ^6.9.0

  # ðŸ Ð”Ð»Ñ Ð³ÐµÐ½ÐµÑ€Ð°Ñ†Ð¸Ð¸ Ð°Ð´Ð°Ð¿Ñ‚ÐµÑ€Ð¾Ð² Hive
  hive_generator: ^2.0.1